name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: true 
      - run: pnpm i 
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
